=== {learning-goals}

## LZ 1
### Grundlagen

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1 - Data Engineering
Die Teilnehmer:innen können erläutern, was Data Engineering ist und kennen übliche Definitionen. Die Teilnehmer:innen können erklären, wie sich die Data Engineering entwickelt hat, um den Anforderungen von Data Science und Data Analytics hinsichtlich Datensammlung, -speicherung, -verarbeitung und -analyse zu entsprechen.

[[LZ-1-2]]
==== LZ 1-2 - Unterscheidung operativer und analytischer Daten
Die Teilnehmer:innen können die Unterschiede hinsichtlich Verwendung, Struktur und Kontext zwischen operativen und analytischen Daten erläutern. Sie können die Begriffe OLTP und OLAP unterscheiden. Ihnen ist klar, warum operative und analytische Daten üblicherweise separat verarbeitet werden und sie kennen typische Beispiele für operative und analytische Anwendungen.     
Sie können die folgenden Eigenschaften analytischer Daten erläutern:

- subjektorientiert
- beständig
- integrierbar
- historisiert

Die Teilnehmer:innen kennen Beispiele, wie analytische Daten aus operativen Anwendungen entstehen. Sie kennen ebenfalls Beispiele, wie Ergebnisse von Analysen analytischer Daten in operativen Anwendungen genutzt werden können.

[[LZ-1-3]]
==== LZ 1-3 - Kategorien der Datenanalyse
Die Teilnehmer:innen kennen die typischen Kategorien der Datenanalyse, können diese unterscheiden und jeweils Beispiele dazu nennen:

- Deskriptive Analyse z.B. Berichtswesen
- Explorative Analyse z.B. Ad-Hoc Reporting
- Inferentielle Analyse: Ableitung von Aussagen aus Stichproben, z.B. Wirksamkeitsanalyse von Medikamenten 
- Prädiktive Analyse: zukünftige Vorhersagen basierend auf historische Daten, z.B. Kreditrisikobewertung
- Kausale Analyse: Erkennung von Ursache-Wirkung-Beziehungen
- Mechanistische Analyse: Integration spezifischen Fachwissens, z.B. physikalischer, biologischer oder chemischer Modelle

[[LZ-1-4]]
==== LZ 1-4 - Herausforderungen analytischer Anwendungen
Die Teilnehmer:innen können übliche Herausforderungen bei Konzeption, Umsetzung und Betrieb analytischer Anwendungssysteme speziell im Hinblick auf die folgenden Voraussetzungen bennenen:

- Umfang und Komplexität der zu verarbeitenen Daten
- Komplexität und Anzahl der Analysen, Anfragen / Queries
- Verfügbarkeit
- Datensicherheit

[[LZ-1-5]]
==== LZ 1-5 - Rollen im Data Engineering
Die Teilnehmer:innen können Rollen wie Data Architect, Data Analyst, Machine Learning Engineer und Data Scientist beschreiben und voneinander abgrenzen. 

Den Teilnehmer:innen ist bewusst, dass die Ausprägung der jeweiligen Rollen von der Effizienz und Professionalität der jeweiligen Organisationen im Hinblick auf die Arbeit mit Daten abhängen.

[[LZ-1-6]]
==== LZ 1-6 - Monolithische und verteilte Datenarchitekturen
Die Teilnehmer:innen verstehen die Vor- und Nachteile monolithischer und verteilter Softwarearchitekturen für analytische Anwendungen. 

Die Teilnehmer:innen wissen, dass analytische Anwendungen bisher häufig eine monolithische Architektur haben und dass mit der Diskussion um Data Mesh (siehe <<LZ-10-1>>) aktuell ein Paradigmenwandel stattfindet.

[[LZ-1-7]]
==== LZ 1-7 - Lebenszyklus analytischer Daten
Die Teilnehmer:innen können die folgenden Phasen der Datenverarbeitung zur Vereinheitlichung analytischer Daten unterscheiden:

- Sources - Das Erzeugen der Daten (siehe <<LZ-3-1>>)
- Ingestion und Transport - Das Extrahieren der Daten und deren Transport zum den Speichersystemen (siehe <<LZ-4-1>>)
- Storage - Das Abspeichern der Daten (siehe <<LZ-5-1>>)
- Query und Processing - Code zur Verarbeitung und Abfragen gegen die gespeicherten Daten (siehe <<LZ-6-1>>)
- Transformation - Transformation der Daten in eine für die Analyse geeignete Form (siehe <<LZ-7-1>>)
- Analysis und Output - Präsentation der Daten für die Analyse und deren Ergebnisse sowie Integration der Analysemöglichkeiten in Anwendungen (siehe <<LZ-8-1>>)

Den Teilnehmer:innen ist bewußt, dass begleitend zu diesen Phasen auch die folgenden Querschnittsthemen zu beachten sind:

- Data Discovery - Information bereitstellen, welche Daten es gibt, wie sie aufbereitet und wo sie zu finden sind
- Data Governance - Erarbeiten und Überwachen allgemein gültiger Regeln für die Verarbeitung der Daten (siehe <<LZ-11-1>>)
- Data Security - Gewährleisten eines angemessenen Grads an Datenschutz (siehe <<LZ-11-2>>)
- Data Quality - Gewährleisten eines angemessenen Grads an Datenqualität (siehe <<LZ-11-3>>)

[[LZ-1-8]]
==== LZ 1-8 - Abgrenzung von anderen iSAQB Modulen
Die Teilnehmer:innen wissen, wie sich dieses Modul von anderen iSAQB Modulen speziell im Hinblick auf Architekturen für Data Science und Architekturen für operative Anwendungssysteme abgrenzt.

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Data engineering
tbd.

[[LG-1-2]]
==== LG 1-2: Differentiation beween operative and analytical data 
tbd.

[[LG-1-3]]
==== LG 1-3: Categories of data analysis
tbd.

[[LG-1-4]]
==== LG 1-4: Challenges of analytical applications
tbd.

[[LG-1-5]]
==== LG 1-5: Roles in  data engineering
tbd.

[[LG-1-6]]
==== LG 1-6: Monolitic and distributed data architectures
tbd.

[[LG-1-7]]
==== LG 1-7: Lifecycle of analytical data
tbd.

[[LG-1-8]]
==== LG 1-8: Distinction from other iSAQB modules
tbd.

// end::EN[]


