=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Datenbezogene Stakeholder und Disziplinen
* Die Teilnehmer wissen, dass Daten für eine gegebene Aufgabenstellung (u.a. unter dem Gesichtspunkt einer datenintensiven
Anwendung) eine zentrale Rolle einnehmen.
* Die Teilnehmer kennen unterschiedliche Einsatzbereiche und daraus resultierend auch unterschiedliche Strategien für Daten und deren Persistenz.
** Beispielhafte Use-Cases aus verschiedenen Bereichen: Gesundheitssektor, Versicherungs-/Finanzwesen,
Telekommunikation, Automobil-/Fertigungsindustrie, Luft-/Raumfahrt, Bildung, Wissenschaft, Forschung
* Die Teilnehmer wissen, dass Architekturen in Bezug auf die Qualitätsmerkmale optimiert werden können. Sie verstehen, warum
die Merkmale _Verfügbarkeit, Zuverlässigkeit, Wartbarkeit_ wichtige Entscheidungskriterien für Datenstrategien darstellen.
* Die Teilnehmer kennen das CAP-Theorem und können die Eigenschaften (A)tomicity\(C)onsistency(I)solation(D)urability oder
(B)asically(A)vailable(S)oft State(E)ventual Consistency entsprechend einordnen.
* Die Teilnehmer kennen unterschiedliche, technologische Aspekte zur Datenerhebung/-transfromation/-übertragung und -analyse
und deren Einsatzzweck.
** Beispielhafte technologische Einsatzzwecke: Business/Customer Intelligence, Real-Time/Streaming-Lösungen, Data Warehouse,
Datenintegration, Advanced Analytics
* Die Teilnehmer können die Stakeholder identifizieren und deren Anforderungen und Einfluss auf die Daten bewerten.

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Data related stakeholders and disciplines


[[LG-1-2]]
==== LG 1-2: Data sources & technical qualities of data
tbd.

[[LG-1-3]]
==== LG 1-3: Legal compliance and established measurements regarding licensing, data security and privacy
tbd.

[[LG-1-4]]
==== LG 1-4: Methods for developing data centric solutions
tbd.

[[LG-1-5]]
==== LG 1-5: Data Lifecycle Management
tbd.

[[LG-1-6]]
==== LG 1-6: Overall data modelling and communication patterns
tbd.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
