=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1 - Unterscheidung operativer und analytischer Daten
Die Teilnehmer:innen können den Unterschied zwischen operativen und analytischen Daten erläutern. Sie können die Begriffe OLTP und OLAP unterscheiden. Sie kennen typische Beispiele für opreative Anwendungen und wissen, welche iSAQB Module sich spezifisch mit der Architektur operativer Anwendungssysteme befassen.
Den Teilnehmer:innen ist klar, warum operative und analytische Daten üblicherweise separat verarbeitet werden. Sie können die folgenden Eigenschaften analytischer Daten erläutern:

- subject-oriented
- nonvolatile
- integrated
- time variant

Die Teilnehmer:innen kennen Beispiele, wie analytische Daten aus operativen Anwendungen entstehen. Sie kennen ebenfalls Beispiele, wie Ergebnisse von Analysen analytischer Daten in operativen Anwendungen genutzt werden können.

[[LZ-1-2]]
==== LZ 1-2 - Analytische Anwendungen
Die Teilnehmer:innen kennen typische Beispiele für analytische Anwendungen (Berichtswesen, Markt- und Kundenanalyse, Operations Research, KPI, Warenkorbanalyse, Regressionsanalyse, Risikoanalyse, Trendanalyse, etc.) und können Typen von Nutzern (Farmer, Explorer, Miner, Tourist, ...) unterscheiden.

Die Teilnehmer:innen können übliche Herausforderungen bei Konzeption, Umsetzung und Betrieb analytischer Anwendungssysteme speziell im Hinblick auf die folgenden Aspekte bennenen:

- Umfang und Komplexität der zu verarbeitenen Daten
- Komplexität und Anzahl der Analysen, Anfragen / Queries
- Verfügbarkeit
- Datensicherheit

[[LZ-1-3]]
==== LZ 1-3 - Kategorien analytischer Anwendungen
Die Teilnehmer:innen kennen die typischen Kategorien analytischer Anwendungen, können diese unterscheiden und jeweils Beispiele dazu nennen:

- Explorativ vs konfirmatorisch
- Deskriptiv, diagnostisch vs präskriptiv
- Inferentiell vs prediktiv
- Realtime, near realtime vs batch

[[LZ-1-4]]
==== LZ 1-4 - Historie der Umsetzung analytischer Anwendungssysteme
Die Teilnehmer:innen haben einen Überblick, wie analytische Anwendungssysteme im Laufe der Zeit umgesetzt worden sind.
Sie kennen Begriffe wie Reporting, DSS, EIS, DWH, Data Mart, Data Vault, Data Mining, ODS, Data Lake, Data Fabric, Data Mesh. Sie können diese Lösungsansätze unterscheiden und wissen, wie sie auseinander hervorgegangen sind.

[[LZ-1-5]]
==== LZ 1-5 - Qualität von Daten
Die Teilnehmer:innen kennen typische Qualitätsmerkmale von Daten und können diese erläutern:

[frame=none, grid=none]
|===
a|
- Genauigkeit
- Verfügbarkeit
- Vollständigkeit
- Aktualität
- Konsistenz
- Privatheit
- Sicherheit
- Vergleichbarkeit
- Granularität
- Glaubwürdigkeit a|
- Plausibilität
- Validität
- Relevanz
- Nützlichkeit
- Eindeutigkeit
- Zuverlässigkeit
- Konformität
- Einheitlichkeit
- Dauerhaftigkeit
- Interpretierbarkeit
|===


Die Teilnehmer:innen verstehen, warum die Gewährleistung von Datenqualität bei analytischen Daten eine besondere Herausforderung ist. Sie kennen Beispiele für Verfahren zur Prüfung, Gewährleistung und Verbesserung analytischer Daten wie etwa:

- Identifikation von Entitäten und Deduplizierung
- Rechtschreibprüfung und -korrektur
- Schema Vorgabe und Anwendung (Data Constraints)
- Prüfsummen
- Beschreibende fachliche Metadaten
- (Standard-) Datenaustauschformate
- Erkennen von Ausreißern (Outlier Detection), fehlenden Werten und Widersprüchen
// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Data related stakeholders and disciplines
tbd.

[[LG-1-2]]
==== LG 1-2: Data sources & technical qualities of data
tbd.

[[LG-1-3]]
==== LG 1-3: Legal compliance and established measurements regarding licensing, data security and privacy
tbd.

[[LG-1-4]]
==== LG 1-4: Methods for developing data centric solutions
tbd.

[[LG-1-5]]
==== LG 1-5: Data Lifecycle Management
tbd.

[[LG-1-6]]
==== LG 1-6: Overall data modelling and communication patterns
tbd.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
