=== {learning-goals}

## LZ 1
### Grundlagen

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1 - Data Engineering
Die Teilnehmer:innen können erläutern was Data Engineering ist und kennen übliche Definitionen. Die Teilnehmer:innen können erklären, wie sich die Data Engineering entwickelt hat um den Anforderungen von Data Science und Data Analytics hinsichtlich Datensammlung, -speicherung, -verarbeitung und -analyse zu entsprechen.

[[LZ-1-2]]
==== LZ 1-2 - Unterscheidung operativer und analytischer Daten
Die Teilnehmer:innen können die Unterschiede hinsichtlich Verwendung, Struktur und Kontext zwischen operativen und analytischen Daten erläutern. Sie können die Begriffe OLTP und OLAP unterscheiden. Ihnen ist klar, warum operative und analytische Daten üblicherweise separat verarbeitet werden und sie kennen typische Beispiele für operative Anwendungen.     
Sie können die folgenden Eigenschaften analytischer Daten erläutern:

- subjektorientiert
- beständig
- integrierbar
- historisiert

Die Teilnehmer:innen kennen Beispiele, wie analytische Daten aus operativen Anwendungen entstehen. Sie kennen ebenfalls Beispiele, wie Ergebnisse von Analysen analytischer Daten in operativen Anwendungen genutzt werden können.

[[LZ-1-3]]
==== LZ 1-3 - Kategorien analytischer Anwendungen
Die Teilnehmer:innen kennen typische Beispiele für analytische Anwendungen, insbesondere Business Intelligence Systeme, Datenvisualisierung, CRM Analytics, IoT Analytics sowie Compliance-Prüfungen und können Typen von deren Nutzern unterscheiden.

Die Teilnehmer:innen können übliche Herausforderungen bei Konzeption, Umsetzung und Betrieb analytischer Anwendungssysteme speziell im Hinblick auf die folgenden Voraussetzungen bennenen:

- Umfang und Komplexität der zu verarbeitenen Daten
- Komplexität und Anzahl der Analysen, Anfragen / Queries
- Verfügbarkeit
- Datensicherheit

Die Teilnehmer:innen kennen die typischen Kategorien analytischer Anwendungen, können diese unterscheiden und jeweils Beispiele dazu nennen:

- Deskriptive Analyse
- Explorative Analyse
- Inferentielle Analyse
- Prädiktive Analyse
- Kausale Analyse
- Mechanistische Analyse

Die Teilnehmer:innen verstehen welche unterschiedlichen Herausforderungen sich durch Datenweitergabe innerhalb beziehungsweise ausserhalb der eigenen Organisation beziehungsweise an Endnutzer ergeben.

Sie können die verschiedenen Bedarfe von datenintensiven Anwendungen einordnen.

[[LZ-1-4]]
==== LZ 1-4 - Entwickler analytischer Anwendungen
Die Teilnehmer:innen können die Rollen von Data Architects, Data Engineers und Data Scientists beschreiben und voneineander abgrenzen. 

Die Teilnehmer:innen kennen Modelle für Reifegrade von Organisationen, die mit Daten arbeiten, sowie von deren Data Engineers und Data Architects.

Die Teilnehmer:innen wissen, wie sich dieses Modul von anderen iSAQB Modulen in Hinsicht auf Data Science und Software Engineering abgrenzt.

[[LZ-1-5]]
==== LZ 1-5 - Monolithische und verteilte Datenarchitekturen
Die Teilnehmer:innen verstehen die Vor- und Nachteile von monolithischen beziehungsweise verteilten Softwarearchitekturen für analytische Anwendungen. 

Die Teilnehmer:innen wissen, dass historisch gesehen ein großer Teil analytischer Anwendungen eine monolithische Architektur haben, woher diese Entwicklung kommt und warum mit Data Mesh (Block 11) hier ein Paradigmenwandel stattfindet.

[[LZ-1-6]]
==== LZ 1-6 - Lebenszyklus analytischer Daten
Die Teilnehmer:innen können die grundsätzlichen Phasen im Lebesnszyklus analytischer Daten benennen, also deren Generierung, Sammlung, Speicherung und Transformation bis hin zur Bereitstellung und Auswertung. Sie wissen welche querschnittlichen Themen in allen Phasen zu beachten sind.

[[LZ-1-7]]
==== LZ 1-7 - Abgrenzung von anderen iSAQB Modulen
Die Teilnehmer:innen wissen, wie sich dieses Modul von anderen iSAQB Modulen in Hinsicht auf Architekture für Data Science und Architektur operativer Anwendungssysteme abgrenzt.

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Data related stakeholders and disciplines
tbd.

[[LG-1-2]]
==== LG 1-2: Data sources & technical qualities of data
tbd.

[[LG-1-3]]
==== LG 1-3: Legal compliance and established measurements regarding licensing, data security and privacy
tbd.

[[LG-1-4]]
==== LG 1-4: Methods for developing data centric solutions
tbd.

[[LG-1-5]]
==== LG 1-5: Data Lifecycle Management
tbd.

[[LG-1-6]]
==== LG 1-6: Overall data modelling and communication patterns
tbd.

// end::EN[]


