=== {learning-goals}

## LZ 1
### Allgemein

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1 - Unterscheidung operativer und analytischer Daten
Die Teilnehmer:innen können den Unterschied zwischen operativen und analytischen Daten erläutern. Sie können die Begriffe OLTP und OLAP unterscheiden. Sie kennen typische Beispiele für opreative Anwendungen und wissen, welche iSAQB Module sich spezifisch mit der Architektur operativer Anwendungssysteme befassen.
Den Teilnehmer:innen ist klar, warum operative und analytische Daten üblicherweise separat verarbeitet werden. Sie können die folgenden Eigenschaften analytischer Daten erläutern:

- subject-oriented
- nonvolatile
- integrated
- time variant

Die Teilnehmer:innen kennen Beispiele, wie analytische Daten aus operativen Anwendungen entstehen. Sie kennen ebenfalls Beispiele, wie Ergebnisse von Analysen analytischer Daten in operativen Anwendungen genutzt werden können.

[[LZ-1-2]]
==== LZ 1-2 - Kategorien analytischer Anwendungen
Die Teilnehmer:innen kennen typische Beispiele für analytische Anwendungen (Berichtswesen, Markt- und Kundenanalyse, Operations Research, KPI, Warenkorbanalyse, Regressionsanalyse, Risikoanalyse, Trendanalyse, etc.) und können Typen von Nutzern (Farmer, Explorer, Miner, Tourist, ...) unterscheiden.

Die Teilnehmer:innen können übliche Herausforderungen bei Konzeption, Umsetzung und Betrieb analytischer Anwendungssysteme speziell im Hinblick auf die folgenden Aspekte bennenen:

- Umfang und Komplexität der zu verarbeitenen Daten
- Komplexität und Anzahl der Analysen, Anfragen / Queries
- Verfügbarkeit
- Datensicherheit

Die Teilnehmer:innen kennen die typischen Kategorien analytischer Anwendungen, können diese unterscheiden und jeweils Beispiele dazu nennen:

- Deskriptive Analyse
- Explorative Analyse
- Inferentielle Analyse
- Prädiktive Analyse
- Kausale Analyse
- Mechanistische Analyse

Die Teilnehmer:innen verstehen welche Unterschiede sich durch Datenweitergabe innerhalb und ausserhalb der eigenen Organisation ergeben.

Die Teilnehmer:innen kennen Beispiele für typische Anwendungen, in denen mit großen Datenmengen umgegangen wird.
Sie können die verschiedenen Bedarfe von datenintensiven Anwendungen einordnen.

Die Teilnehmer:innen wissen, wie sich dieses Modul von anderen iSAQB Modulen abgrenzt.

[[LZ 1-3]]
==== LZ 1-2 - Entwickler analytischer Anwendungen
Die Teilnehmer:innen können die Rollen von Data Architects, Data Engineers und Data Scientists beschreiben und voneineander abgrenzen. 

Die Teilnehmer:innen kennen Modelle für Reifegrade von Organisationen, die mit Daten arbeiten, sowie von deren Data Engineers und Data Architects.

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Data related stakeholders and disciplines
tbd.

[[LG-1-2]]
==== LG 1-2: Data sources & technical qualities of data
tbd.

[[LG-1-3]]
==== LG 1-3: Legal compliance and established measurements regarding licensing, data security and privacy
tbd.

[[LG-1-4]]
==== LG 1-4: Methods for developing data centric solutions
tbd.

[[LG-1-5]]
==== LG 1-5: Data Lifecycle Management
tbd.

[[LG-1-6]]
==== LG 1-6: Overall data modelling and communication patterns
tbd.

// end::EN[]


