= https://isaqb.org[iSAQB] Advanced Level Curriculum DATA

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-data/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-data/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-data.svg["Contributors",link="https://github.com/isaqb-org/curriculum-data/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-data.svg["Issues",link="https://github.com/isaqb-org/curriculum-data/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-data.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-data/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the iSAQB Advanced Level curriculum DATA in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

. Clone the repository—including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-data.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-data.git --recursive
----
--

. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK) via `./gradlew buildDocs`.
. Once "BUILD SUCCESSFUL" is shown, you can review the build result under `./build/index.html`

That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Christine Koppelt and Rainer Jaspert.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
