=== {learning-goals}


// tag::DE[]
[[LZ-10-1]]
==== LZ 10-1 Was sind Data Pipelines
Die Teilnehmer wissen, dass Daten in Produktion vorher durch verschiedene Stages gelaufen sind. Sie kennen die üblichen Stage Bezeichnungen und wissen was typischerweise mit Data Pipelines in den Stages gemacht wird:

- Ingestion
- Transport
- Storage
- Transformation
- Presentation

Die Teilnehmer wissen auch, dass diese einzelnen an Data Pipelines der Stages zu größeren Data Pipelines zusammengesetzt werden können.

Außerdem wissen die Teilnehmer wozu Data Pipelines verwendet werden. Die Teilnehmer kennen daher die wesentlichen Eigenschaften die Data Pipelines bieten:

- Accessible
- Scalable
- Monitored
- Efficient

[[LZ-10-2]]
==== LZ 10-2 Arten von Data Pipelines
Die Teilnehmer wissen um die verschiedenen Arten von Data Pipelines. Sie wissen in welchen Situationen diese zum Einsatz kommen und wann sie vorteilhaft sind. Sie kennen daher die Unterscheidungen zwischen:

- ETL vs ELT
- reverse ETL
- Microbatches vs Stream

Außerdem kennen die Teilnehmer typische Anwendungsgebiete von Data Pipelines:

- Data Engineering
- Analytics/ML Processing
- Delivery

[[LZ-10-3]]
==== LZ 10-3 Data Pipeline Qualitätskriterien
Die Teilnehmer kennen Qualitätskriterien, die die Güte einer Data Pipeline beschreiben. Sie verstehen daher die folgenden Begriffe und wissen, was diese für eine Data Pipeline bedeuten:

- Throughput
- Reliability
- Latency
- Stability

[[LZ-10-4]]
==== LZ 10-4 Building Blocks von Data Pipelines
Die Teilnehmer wissen aus welchen Building Blocks eine Data Pipelines besteht. Sie kennen Beispiele dieser Blocks und wissen wann welches Tooling für einen Anwendungsfall geeignet ist.

Hierfür kennen sie die folgenden Begriffe, kennen Tools für diese und wissen in welchen Kombinationen diese mit anderen Tools verwendet werden können:

- Scheduler
- Workflow Engine
- Query Engine
- HTTP/MQTT Endpoints
- Message Broker
- Low Cost/High Volume Data Storage
- Stream Processing Engine
- Data Catalog
- ML Framework

[[LZ-10-5]]
==== LZ 10-5 Technologien/Tools für Data Pipelines
Die Teilnehmer kennen Technologien, wie SQL, Python Dataframes oder Spark, mit denen Data Pipelines selbst erstellt werden können. Sie kennen aber auch Tools um Data Pipelines zu erstellen, wie z.B.:

- Apache Airflow
- Databricks
- Fivetran
- Astera Centerprise
- Skyvia

[[LZ-10-6]]
==== LZ 10-6 Monitoring
Die Teilnehmer wissen, dass für die Data Pipeline ein Monitoring notwendig ist, um die Performanz und Qualität der Verarbeitung sicherzustellen.

Die Teilnehmer verstehen, dass das Monitoring dabei relevante Buisness Metriken umfassen muss, welche von der Anwendung abhängig sind und an diese angepasst werden müssen.

Den Teilnehmern ist bewusst, dass in einer Cloud Umgebung zusätzliche Eigenschaften beobachtet werden müssen, wie z.B.:

- Latenz
- Häufigkeit von Systemfehlern
- Datenmenge
- Auslastung

[[LZ-10-7]]
==== LZ 10-7 Optimization
Den Teilnehmern ist bewusst, dass Data Pipelines sehr häufig automatisiert laufen und wissen, dass Optimierung daher eine große Rolle für Data Pipelines spielt. Die Teilnehmer kennen daher Möglichkeiten eine Laufzeitanalyse für Data Pipelines aufzusetzen und wissen falls nötig dann wie sie die Laufzeiten der Operationen optimieren können.

[[LZ-10-8]]
==== LZ 10-8 Cloud vs on-Premise
Den Teilnehmern ist bewusst, dass Data Pipelines sowohl in on-Premise als auch in Cloud Umgebungen etabliert werden können.
Die Teilnehmer kennen die Vor- und Nachteile von Cloud vs on-Premise Datenverarbeitung. Zusätzlich kennen sie die Wirkung von Edge-Computing und wissen wie sich diese auf die Datenverarbeitung auswirkt.

Die Teilnehmer wissen insbesondere, dass Data Pipelines so gestaltet werden können, dass sie sowohl in der Cloud als auch on-premise ausführbar sind, sodass ein Setup ggfs. in das andere übertragen werden kann.
// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Aspects and building blocks
tbd.

[[LG-6-2]]
==== LG 6-2: Central approaches
tbd.

[[LG-6-3]]
==== LG 6-3: Data Mesh
tbd.

[[LG-6-4]]
==== LG 6-4: Machine Learning
tbd.

[[LG-6-5]]
==== LG 6-5: Use Cases
tbd.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
