=== {learning-goals}


// tag::DE[]
[[LZ-9-1]]
==== LZ 9-1 - Bedeutung von Datenmodellen
Den Teilnehmern ist der Umgang mit Datenmodellen generell vertraut. Sie verstehen, wie Datenmodelle für die Arbeit mit analytischen Daten sich sowohl an den Datenmodellen der Quellsysteme als auch an den Anforderungen an die Datenanalyse orientieren müssen. Sie kennen die Unterscheidung konzeptioneller, logischer und physischer Datenmodelle.
Die Teilnehmer verstehen den Begriff der Granularität eines Datenmodells.

[[LZ-9-1]]
==== LZ 9-2 - Normalisierung von Datenmodellen
Die Teilnehmer kennen das Konzept der Normalisierung von Datenmodellen. Sie verstehen, dass für die Arbeit mit analytischen Daten häufig auf die Normalisierung verzichtet wird und die Verwendung denormaliserter Datenmodelle in diesem Umfeld nicht unüblich ist.

[[LZ-9-1]]
==== LZ 9-3 - Änderung von Datenmodellen
Die Teilnehmer verstehen, dass Datenmodelle sowohl im Hinblick auf die verwendeten Quellsysteme als auch, noch weit deutlicher, im Hinblick auf die analytischen Anwendungen, Änderungen unterworfen sind.
Die Teilnehmer kennen Ansätze, wie mit entsprechenden Änderungen umgegangen werden kann, wie etwa

- Verwendung multidimensionaler Datenmodelle (Star, Snowflake, Data Vault)
- Zerlegung in Teil-Modelle (s. LZ 11-2 - Domain Ownership)
- Automatisierung der Modell-Änderungen (DWH Automation)
// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Aspects and building blocks
tbd.

[[LG-6-2]]
==== LG 6-2: Central approaches
tbd.

[[LG-6-3]]
==== LG 6-3: Data Mesh
tbd.

[[LG-6-4]]
==== LG 6-4: Machine Learning
tbd.

[[LG-6-5]]
==== LG 6-5: Use Cases
tbd.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
