=== {learning-goals}


// tag::DE[]
[[LZ-8-1]]
==== LZ 8-1 - Anwendungsfälle
Die Teilnehmer:innen können die wesentlichen Anwendungsfälle für die Nutzung analytischer Daten unterscheiden:

- Basis für Data Analytics und Business Intelligence (BI)
- Test- und Trainingsdaten für das Erstellen und Verbessern von Maschine Learning Modellen
- Bereitstellen der Ergebnisse analytischer Auswertungen für die Verwendung in operativen Anwendungen (Reverse ETL)

[[LZ-8-2]]
==== LZ 8-2 - Repräsentation von Massendaten
Die Teilnehmer:innen wissen wie die Verfahren des Query-Processings wie Aggregation oder Cubes für die Darstellung von Massendaten verwendet werden können. Ihnen ist bewusst, dass bei analytischen Daten die Vertrauenswürdigkeit eine zentrale Rolle spielt. Sie wissen, dass daher neben den Daten selbst auch Information zu deren Schema, zum Umfang, zur Aktualität, zu den Datenquellen oder zur Qualität angeboten werden können.

Die Teilnehmer:innen kennen Tools zur Visualisierung von Massendaten. Sie kennen verfügbare Arten von Diagrammen (Heatmap, Ranking, Top, ...) und können diese speziell im Hinblick auf Kosten/Nutzen beurteilen. Sie kennen BI-/Reporting Tools und wissen, wie diese für explorative (Slice & Dice, Drill, etc) oder descriptive Analysen eingesetzt werden können. Die Teilnehmer:innen wissen, dass auf Basis dieser Tools analytische Anwendungen wie Dashbords umgesetzt werden können.

[[LZ-8-3]]
==== LZ 8-3 - Modularisierung
Die Teilnehmer:innen wissen, dass analytische Daten vielfältig und unübersichtlich sein können. Sie kennen das Konzept des Datenprodukts und wissen, dass die Datenprodukte verwendet werden können, um analytische Daten fachlich zu zerlegen. Sie kennen speziell deren Verwendung im Data Mesh Ansatz (siehe <<LZ-10-1>>).

[[LZ-8-4]]
==== LZ 8-4 - Data Analytics und Business Intelligence
Den Teilnehmer:innen sind Data Analytics und BI Anwendungen vertraut. Sie kennen Anwendungsfälle für die Analyse operativ anfallender Daten für die Unternehmenssteuerung.

Die Teilnehmer:innen kennen Frameworks und Tools für die Umsetzung von Data Analytics und BI Anwendungen. Ihnen ist bewusst, das diese Anwendungen üblicherweise direkten Zugriff auf die zugrundeliegenden Speichersysteme benötigen.

[[LZ-8-5]]
==== LZ 8-5 - Machine Learning
Die Teilnehmer:innen wissen, wie Machine Learning Modelle für den Einsatz im Unternehmen auf Basis operativ anfallender Daten trainiert, verbessert und getestet werden. Sie kennen Anwendungsfälle für die Nutzung solcher Modelle in operativen Anwendungen. Ihnen ist bewusst, das ML Verfahren, anders als Data Analytics, auf einen Extract der vollständigen Rohdaten angewiesen sind und spezielle Repräsentationen (Vektoren) benötigen. Sie kennen die häufige Notwendigkeit spezialiserter Hardware (GPUs).

[[LZ-8-6]]
==== LZ 8-6 - Reverse ETL
Den Teilnehmer:innen ist das Konzept der Reverse ETL vertraut. Sie kennen Anwendungsfälle für die Integration von vereinheitlichten Daten oder von Ergebnissen analytischer Auswertungen in operative Anwendungen.

Die Teilnehmer:innen wissen, dass Reverse ETL Tools mit Konnektoren für gängige operative Anwendungen existieren, die die Umsetzung entsprechender Integrationslösungen deutlich erleichtern. Sie kennen Beispiele für diese Tools.
// end::DE[]

// tag::EN[]
[[LG-8-1]]
==== LG 6-1: Use Cases
tbd.

[[LG-8-2]]
==== LG 6-2: Representation of mass data
tbd.

[[LG-8-3]]
==== LG 6-3: Modularization
tbd.

[[LG-8-4]]
==== LG 6-4: Data Analytics and Business Intelligence
tbd.

[[LG-8-5]]
==== LG 8-5: Machine Learning
tbd.

[[LG-8-6]]
==== LG 8-6: Reverse ETL
tbd.

// end::EN[]

