=== {learning-goals}


// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Dies ist das erste Lernziel in Kapitel 6, lorem ipsum sit dolor

Hier wird beschrieben, was Teilnehmer:innen in diesem Lernziel lernen sollen. Das kann in Prosa-Text
in ganzen Sätzen oder in Aufzählungen mit Unterpunkten erfolgen. Dabei kann auch unterschieden werden,
wie wichtig einzelne Aspekte des Lernziels sind. Es kann hier bereits auf Literatur verwiesen werden.

* Erstes Teilziel
* Zweites Unterthema
* Dritter Aspekt

[[LZ-6-2]]
==== LZ 6-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.
// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Aspects and building blocks
tbd.

[[LG-6-2]]
==== LG 6-2: Central approaches
tbd.

[[LG-6-3]]
==== LG 6-3: Data Mesh
tbd.

[[LG-6-4]]
==== LG 6-4: Machine Learning
tbd.

[[LG-6-5]]
==== LG 6-5: Use Cases
tbd.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
