=== {learning-goals}


// tag::DE[]

[[LZ-6-1]]
==== LZ 6-1 - Analytische Querys
Die Teilnehmer:innen verstehen, dass sich analytische Queries stets lesend auf eine größere Anzahl von Datensätzen beziehen. Sie wissen, dass diese Daten für die Analyse sowohl komplett abgespeichert (Data in Rest) als auch im Fluss (Data in Motion) sein können.

Die Teilnehmer:innen kennen spezifische Muster für analytischer Queries etwa

- Aggregationen (Sum, Count, Avg, ...)
- Fenstern/Windows (Over Partition by)
- OLAP Operationen (Slice/Dice, Drill up/down/...)
- Umformungen (Pivot, Transpose, ...)
- Modularisierung (Views, Common Table Expressions, Stored Procedures, User Defined Functions)

[[LZ-6-2]]
==== LZ 6-2 - Query Programmiermodelle
Die Teilnehmer:innen wissen, dass unterschiedliche Programmiermodelle für analytische Queries eingesetzt werden. Ihnen sind wesentliche Programmiermodelle bekannt und sie können beurteilen, für welche Aufgaben sie speziell geeignet sind:

- SQL
- OLAP
- Spark
- Map-Reduce
- Stream Processing
- Dataframes
- Numerical/Statistical

Den Teilnehmer:innen ist bewusst, dass die Art des benötigten Datenzugriffs zentral für die Wahl einer Datenarchitektur ist.

Die Teilnehmer:innen kennen für jedes dieser Programmiermodelle Beispiele zu Frameworks, Libraries und Tools für die Verarbeitung analytischer Queries.

[[LZ-6-2]]
==== LZ 6-2 - Query Verarbeitung & Optimierung
Die Teilnehmer:innen wissen, dass die Verarbeitung der Queries von der sog. Query-Engine übernommen werden. Die Teilnehmer:innen wissen, dass diese Engines sehr eng an ein verwendetes Datenbanksystem gekoppelt sein können, dass es aber auch Engines gibt, die davon unabhängig arbeiten.

Den Teilnehmer:innen ist bekannt, dass die Verarbeitung von Queries in den folgenden Schritten erfolgt:

- Parsen der Query-Statements
- Erstellen und Optimieren des Ausführungsplans
- Ausführen der Query gemäß Ausführungsplan
- Rückgabe der Ergebnisse

Die Teilnehmer:innen verstehen, dass analytische Queries i.d.R. nicht komplett im Hauptspeicher verarbeitet werden können und dass analytische Queries oft auf verteilten Daten operieren müssen. Sie wissen, dass eine performante Ausführung von der Engine insbesondere durch Lastverteilung auf parallel arbeitende Worker gewährleistet werden kann.

Den Teilnehmer:innen ist bewusst, dass Unterschiede in Ausführungsplänen zu drastischen Laufzeit-Unterschieden bei der Ausführung von Queries führen können. Sie kennen Beispiele wie Full Table Scans oder Full Outer Joins (Kreuzprodukte), die auf ungünstige Ausführungspläne hinweisen können.

Die Teilnehmer:innen kennen gängige Verfahren zur Optimierung (analytischer) Queries, wie etwa die Vorgabe günstiger Join-Beziehungen im Star-Schema.

// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Aspects and building blocks
tbd.

[[LG-6-2]]
==== LG 6-2: Central approaches
tbd.

[[LG-6-3]]
==== LG 6-3: Data Mesh
tbd.

[[LG-6-4]]
==== LG 6-4: Machine Learning
tbd.

[[LG-6-5]]
==== LG 6-5: Use Cases
tbd.

// end::EN[]


