=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Dies ist das erste Lernziel in Kapitel 3, das mit xyz

Hier wird beschrieben, was Teilnehmer:innen in diesem Lernziel lernen sollen. Das kann in Prosa-Text
in ganzen Sätzen oder in Aufzählungen mit Unterpunkten erfolgen. Dabei kann auch unterschieden werden,
wie wichtig einzelne Aspekte des Lernziels sind. Es kann hier bereits auf Literatur verwiesen werden.

* Erstes Teilziel
* Zweites Unterthema
* Dritter Aspekt

[[LZ-3-2]]
==== LZ 3-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: General aspects
tbd.

[[LG-3-2]]
==== LG 3-2: Policies
tbd.

[[LG-3-3]]
==== LG 3-3: Metadata Management
tbd.

[[LG-3-4]]
==== LG 3-4: Data Quality
tbd.

[[LG-3-5]]
==== LG 3-5: Traceability
tbd.

[[LG-3-6]]
==== LG 3-6: Maintainability
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
