=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1 - Arten von Datenquellen und Quellsystemen
Die Teilnehmer:innen kennen Beispiele für inhaltliche und technische Arten von Datenquellen und Quellsystemen, von denen analytische Daten typischerweise übernommen werden, wie etwa:

inhaltliche Quellen

- Sensordaten
- Standard Anwendungen
- Logging Systeme
- (Web-) Analytics
- Metrics Systeme

technische Quellen

- APIs
- Datenbanken
- Event-Feed
- Messaging Systeme
- (Cloud) Storage Systeme


[[LZ-3-2]]
==== LZ 3-2 - Eigenschaften von Datenquellen und Quellsystemen
Die Teilnehmer:innen können unterscheiden, ob Datenquellen strukturierte, semi-strukturierte oder unstukturierte Daten liefern. Ihnen sind übliche Formate vertraut, in denen Datenquellen ihre Daten zur Verfügung stellen, wie etwa

- Dokumente
- Liste von Datensätzen
- Key-value Paare

Den Teilnehmer:innen ist bewusst, dass Quellsysteme z.T. sehr große Datenmengen bereitstellen, und dass geeignete Maßnahmen getroffen werden müssen, um diese Datenmengen transportieren zu können.

Die Teilnehmer:innen wissen, dass das zur Verfügung stellen analytischer Daten zusätzliche Last für das jeweilige Quellsystem erzeugt werden kann und dass dies i.d.R. den eigentlichen Zweck eines Quellsystems nicht beeinträchtigen darf. Den Teilnehmer:innen ist bewusst, dass es durch spezifische technologische oder organisatorische Rahmenbedingungen schwierig sein kann auf die Daten zuzugreifen.

Die Teilnehmer:innen wissen, dass Quellsysteme Daten unter Umständen redundant bereitstellen und können entsprechend mit ihnen umgehen.

Den Teilnehmer:innen ist bewusst, welche Garantien, wie Konsistenz, Integrität, Aktualität, Korrektheit eine Datenquelle zur Verfügung stellen kann.

Die Teilnehmer:innen wissen, dass die Datenmodelle von Quellsystemen veränderbar sind.


[[LZ-3-3]]
==== LZ 3-3 - Eigenschaften von APIs

Den Teilnehmer:innen ist bewusst, das APIs dazu dienen das interne Datenmodell zu abstrahieren und zu definieren was extern bereitgestellt werden soll. Sie kennen zentrale Aspekte beim Entwurf von APIs wie Versionierung und Schemata.

Den Teilnehmer:innen ist bewusst, das APIs üblicherweise vom Quellsystem bereitgestellt werden, aber auch vom Zielsystem angeboten werden können (reverse APIs). Sie kennen Arten von APIs die zur Bereitstellung von Daten dienen wie beispielsweise REST und RPC, Ansätze die Daten direkt transformieren wie GraphQL, sowie Ansätze für reverse APIs wie beispielsweise Webhooks.  


[[LZ-3-4]]
==== LZ 3-4 - Eigenschaften von Datenbanksystemen

Die Teilnehmer:innen wissen, dass Datenbanken durch ein Datenbankmanagementsystem verwaltet werden, welches beispielsweise Schemaverwaltung, Datenzugriff, Query-Optimizer, Datenverteilung bereitstellt. Ihnen ist bewusst, das Datenbanken vorrangig für die Verwaltung strukturierter Daten verwendet werden. Sie sind sich auch der Problematik einer starken Kopplung der Datenmodelle bei direktem Datenbank-Zugriff bewusst. 

Die Teilnehmer:innen kennen den Unterschied zwischen relationalen und nicht-relationalen Datenbanken und kennen Beispiele für nicht-reationale Datenbanken wie Zeitreihen-, Graph- oder Dokumentendatenbanken. 


[[LZ-3-5]]
==== LZ 3-5 - Eigenschaften von Dateisystemen
Die Teilnehmer:innen wissen, dass der Zugriff über Systemaufrufe auf Betriebssystemebene erfolgt.

Den Teilnehmer:innen ist bewusst ... Datenstruktur durch Dateiformat festgelegt.

Einzeldatenzugriff vs.  Zusammengefasst

Dateiübertragung/Zugriff
Replikationsmechanismen
Versionierung
Batch-Verarbeitung


[[LZ-3-6]]
==== LZ 3-6 - Eigenschaften von Object Stores
Die Teilnehmer:innen wissen, das der Zugriff auf die Daten typischerweise durch RESTful APIs erfolgt. Sie wissen, dass Object Stores für die Speicherung großer Mengen unstrukturierter Daten konzipiert sind und sich üblicherweise horizontal sehr gut skalieren lassen.

Garantien - Nebenläufigkeit

* Metadaten: Relativ flexibel

Replkation, Indixierung


[[LZ-3-7]]
==== LZ 3-7 - Eigenschaften von Message Queues und Event-Streaming

Die Teilnehmer:innen wissen, dass beide Ansätzen auf einer asynchronen Bereitstellung von Daten durch das Quellsystem basieren und ein synchroner Zugriff auf das Quellsystem üblicherweise nicht möglich ist. 

Die Teilnehmer:innen kennen den Unterschied zwischen Messaging Systemen und Streaming Ansätzen. Die Teilnehmer:innen wissen, dass Event Streams ein geordnetes Log der bereitgestellten Daten darstellen, welches von verschiedenen Zielsystemen abonniert werden kann aber nicht muss (Publish Subscribe), wohingegen Messaging Systeme die Daten solagen vorhalten, bis sie von einem Zielsystem explizit abgeholt wurden. 

Die Teilnehmer:innen sind sich der Problematik der Übertragung des initialen Zustandes bewusst und kennen Ansätze wie z.B. Snapshots um das Thema zu adressieren.

Den Teilnehmer:innen ist bewusst, dass Daten mehrfach gesendet werden können, da es aufwendig ist sicherzustellen, dass Daten tatsächlich verarbeitet wurden. Sie wissen, dass bei der Verarbeitung auf Idempotenz geachtet werden sollte und kennen Patterns wie dies umgesetzt werden kann.

Den Teilnehmer:innen ist bewusst, dass die Verwendung von Streams zu temporären Inkonsistenzen im Datenbestand führen kann (eventual consistency).


// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: General aspects
tbd.

[[LG-3-2]]
==== LG 3-2: Policies
tbd.

[[LG-3-3]]
==== LG 3-3: Metadata Management
tbd.

[[LG-3-4]]
==== LG 3-4: Data Quality
tbd.

[[LG-3-5]]
==== LG 3-5: Traceability
tbd.

[[LG-3-6]]
==== LG 3-6: Maintainability
tbd.
// end::EN[]


