=== {learning-goals}

// tag::DE[]
[[LZ-2-1]]
==== LZ 2-1 - Überblick zu Referenzarchitekturen
Den Teilnehmer:innen ist der generelle Nutzen von Referenzarchitekturen bewusst:

- eine Vorlage für eine funktionale Zerlegung in wesentliche Bestandteile zur Verfügung zu stellen
- ein einheitliches Vorgehen für die Aufnahme, Verarbeitung und Verwendung von Daten vorzugeben
- dadurch eine Vorlage für die Ausprägung konkreter Software-Architekturen zu bieten

Die Teilnehmer:innen verstehen, dass Referenzarchitekturen für analytische Anwendungssysteme generell unterschieden werden, je nachdem, ob eine Basis für

- die Vereinheitlichung und Integration analytischer Daten
- die Anwendung von Verfahren der KI und des ML auf analytischen Daten (nicht Bestandteil dieses Lehrplans)
- beides zugleich

geschaffen werden soll.

Die Teilnehmer:innen kennen Ansätze, ein einheitliches Framework für Referenzarchitekturen zu analytischen Anwendungssystemen zu beschreiben.

Die Teilnehmer:innen verstehen, dass Referenzarchitekturen sowohl in monolithischen Ansätzen für die Architektur des Gesamtsystem herangezogen werden können, als auch in verteilten Ansätzen wie Data Mesh (siehe <<LZ-10-1>>) für die Architektur jedes Teilsystems eingesetzt werden können.

Die Teilnehmer:innen kennen Beispiele von Referenzarchitekturen für analytische Anwendungssysteme wie etwa

- Data Warehouse
- Data Lake
- Lambda Architecture

[[LZ-2-2]]
==== LZ 2-2 - Referenzarchitekturen zur Vereinheitlichung analytischer Daten
Die Teilnehmer:innen kennen die Phasen der Datenverarbeitung und wissen, welche Toolkategorien in den jeweiligen Phasen typischerweise zum Einsatz kommen (siehe [M. Bornstein 2020]). 

Die Teilnehmer:innen kennen Komponenten die zur Abdeckung querschnittlicher Themen geeignet sind.


[[LZ-2-3]]
==== LZ 2-3 - Architekturentscheidungen anhand von Referenzarchitekturen
Die Teilnehmer:innen können Architekturentscheidungen etwa zu den folgenden Fragestellungen anhand von Referenzarchitekturen diskutieren:

- ob ein zentrales/monolithisches oder dezentrales/förderiertes System zu wählen ist
- ob ein Deployment in der Cloud (ggfs. Cloud-Ready), hybrid oder on-Premise vorzuziehen ist
- ob eine eigenständige Entwicklung von Komponenten erforderlich ist oder das Kaufen und Konfigurieren von Standardkomponenten ausreicht
- ob die Integration von Komponenten selbst vorgenommen oder auf die Verwendung bereits integrierter Komponenten vertraut wird
- ob Stream-, Batch-Processing (ggfs Micro-Batch) oder beides unterstützt werden muss
- welche Form der Skalierbarkeit konkret benötigt wird, z.B. Datenvolumen, Anzahl der Nutzer
- welche Rollen und Verantwortlichkeiten vorgesehen werden müssen
// end::DE[]

// tag::EN[]
[[LG-2-1]]
==== LG 2-1: Overview architectural patterns
tbd.

[[LG-2-2]]
==== LG 2-2: Architectural patterns for for unifying analytical data
tbd.

[[LG-2-3]]
==== LG 2-3: Architecture decisions based on architectural patterns
tbd.

// end::EN[]


