=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Dies ist das erste Lernziel in Kapitel 4, das mit xyz

Hier wird beschrieben, was Teilnehmer:innen in diesem Lernziel lernen sollen. Das kann in Prosa-Text
in ganzen Sätzen oder in Aufzählungen mit Unterpunkten erfolgen. Dabei kann auch unterschieden werden,
wie wichtig einzelne Aspekte des Lernziels sind. Es kann hier bereits auf Literatur verwiesen werden.

* Erstes Teilziel
* Zweites Unterthema
* Dritter Aspekt

[[LZ-4-2]]
==== LZ 4-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Categories of data consumers
tbd.

[[LG-4-2]]
==== LG 4-2: Data providers
tbd.

[[LG-4-3]]
==== LG 4-3: Data presentation patterns
tbd.

[[LG-4-4]]
==== LG 4-4: Predictive techniques
tbd.

[[LG-4-5]]
==== LG 4-5: Integration in operative systems
tbd.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
