=== {learning-goals}

// tag::DE[]

[[LZ-4-1]]
==== LZ 4-1 - Identifizieren von Entitäten
Den Teilnehmer:innen sind Verfahren für das Identifizieren von Entitäten in Quellsystemen bekannt, wie etwa Primary Keys (technische vs. fachliche Schlüssel)

Das Erkennen von Duplikaten ist Bestandteil von Modul 7.

[[LZ-4-2]]
==== LZ 4-2 - Erkennen von Änderungen
Den Teilnehmer:innen sind Verfahren für das Erkennen von Änderungen dieser Entitäten in Quellsystemen bekannt, wie etwa

- Change Data Capture (CDC)
- DB-Trigger
- Create und Update Timestamps

Die Teilnehmer:innen wissen, für welche Art von Quellsystemen welche dieser Verfahren jeweils geeignet sind.

Den Teilnehmer:innen ist bewusst, dass das Löschen von Daten üblicherweise ebenfalls als Änderung geliefert wird, da auch gelöschte Daten für die Analyse ggfs. weiter benötigt werden.

Den Teilnehmer:innen ist bewusst, dass durch den Zugriff auf interne Änderungen des Quellsystems das Prinzip des Information Hidings verletzt werden kann.  Sie verstehen, wie das Outbox Pattern dazu genutzt werden kann, dieses Problem zu adressieren.

[[LZ-4-2]]
==== LZ 4-2 - Konnektoren
Die Teilnehmer:innen kennen Tools und Frameworks, die über vordefinierte Konnektoren einen vereinheitlichten Zugriff auf Quellsysteme zur Verfügung stellen. Sie wissen, dass diese Tools und Frameworks vorrangig für die folgenden Aufgaben eingesetzt werden:

- Datenreplikation
- Datenintegration
- Datenvirtualisierung
- Datenorchestrierung
- Metadatenmanagement

Die Teilnehmer:innen kennen Beispiele für diese Tools.

[[LZ-4-3]]
==== LZ 4-3 - Eigenschaften von Data Ingestion

Die Teilnehmer:innen wissen, das die Data Ingestion unabhängig von der nachfolgenden Datenverarbeitung erfolgt, z.B. hinsichtlich Frequenz des Abrufs.

Die Teilnehmer:innen wissen, das Daten in der Regel kontinuierlich erzeugt werden und für die Verarbeitung in Pakete zerlegt werden können.

Die Teilnehmer:innen kennen die Unterschiede zwischen synchronisierter und nicht-synchronisierter Ingestion und kennen die Probleme, die mit einer synchronisierten Abfolge einhergehen.

Den Teilnehmer:innen ist bewusst, dass Abläufe für die Ingestion skalierbar gestaltet werden sollte, da diese Prozesse häufig große Datenmengen betreffen und ggf. wiederholt ausgeführt werden müssen.

Die Teilnehmer:innen wissen, dass die Ingestion den aktuellen Zustand der zuletzt geänderten Daten (Snapshot) oder die Änderungen selbst (Increments/Events) betreffen kann, mit denen dieser aktuelle Zustand erzeugt wurde. Sie wissen, dass ggfs. eine initiale Bereitstellung (initial Load) der Daten erforderlich ist.

Die Teilnehmer:innen wissen, dass die Datenquellen ihre Daten selbst aktiv liefern können (Push), auf Anfrage einmalig bereitstellen (Pull), oder periodisch bereitstellen können (Poll).

[[LZ-4-4]]
==== LZ 4-4 - Batch vs Stream Ingestion
Den Teilnehmer:innen sind die Verfahren zur Batch- und Stream-Verarbeitung bekannt. Ihnen ist bewusst, wie Batch Verfahren durch zeitliche (Batch) oder größen-basierte (Micro Batch) Pakete aus einem kontinuierlichen Datenstrom der Quellsysteme erstellt werden können.

Die Teilnehmer:innen kennen den Unterschied zwischen dem ELT und dem ETL Pattern.

Den Teilnehmer:innen ist bei der Stream Ingestion bewusst, dass Daten zu spät ankommen können und dass downstream Systeme dies handhaben können müssen.

[[LZ-4-5]]
==== LZ 4-5 - Metadaten
Die Teilnehmer:innen verstehen die Bedeutung von Metadaten für die Nutzung von Datenquellen. Sie können technische und fachliche Metadaten unterscheiden. Sie wissen, dass Quellsysteme oft umfassend Metadaten zu den von ihnen bereitgestellten Datenquellen zur Verfügung stellen.

Die Teilnehmer:innen wissen dass beispielsweise folgende Informationen in Form von Metadaten für Folgesysteme von großem Nutzen:

- Typ (Tabelle, Bild, Text, ...)
- Größe (Bytes, Gigabytes, Terabytes, ...)
- Schema und Datentypen

Die Teilnehmer:innen wissen, dass es Verfahren gibt (Schema Inference), um Metadaten aus Daten abzuleiten. Ihnen ist bewusst, dass sich Metadaten über die Nutzungsdauer von Daten ändern können (Schema Evolution) und dass Verfahren existieren, diese Änderungen beim Zugriff auf die Daten zu erkennen.

Die Teilnehmer:innen wissen, dass Data Catalogs zur Verwaltung der Metadaten verwendet werden können. Sie wissen, dass neben den Metadaten der Datenquelle auch die Ausführung der Ingestion in Data Catalogs festgehalten werden.
// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Categories of data consumers
tbd.

[[LG-4-2]]
==== LG 4-2: Data providers
tbd.

[[LG-4-3]]
==== LG 4-3: Data presentation patterns
tbd.

[[LG-4-4]]
==== LG 4-4: Predictive techniques
tbd.

[[LG-4-5]]
==== LG 4-5: Integration in operative systems
tbd.
// end::EN[]


