=== {learning-goals}


// tag::DE[]

[[LZ-12-1]]
==== LZ 12-1 - Begriffsdefinition
Die Teilnehmer:innen verstehen, dass Data Governance eine Vielzahl von Prinzipien und Praktiken hinsichtlich Qualität, Integrität, Daten- schutz und sicherheit, und
Benutzbarkeit umfasst, die sicherstellen, dass Daten im gesamten Lebenszyklus von der Erstellung bis zur Löschung sicher, effektiv und effizient verwaltet werden.


[[LZ-12-2]]
==== LZ 12-2 - Datenschutz, Compliance, Datensicherheit
Die Teilnehmer:innen kennen Vorgehensweisen und Mechanismen zur Implementierung von Sicherheitsmaßnahmen zum Schutz sensibler Daten.
Die Teilnehmer:innen verstehen, welche Daten anonymisiert oder pseudonymisiert werden müssen und kennen die jeweiligen Nutzungsszenarien.
Die Teilnehmer:innen kennen gängige Praktiken zur Anonymisierung und Pseudonymisierung von Daten und wissen, in welchen Fällen diese angewendet werden.

[[LZ-12-3]]
==== LZ 12-3 - Qualität von Daten
Die Teilnehmer:innen verstehen, warum die Gewährleistung von Datenqualität bei analytischen Daten eine besondere Herausforderung ist. 
Sie verstehen dass sich die Data Governance darum kümmert die Datenqualität zu gewährleisten.
Die Teilnehmer:innen kennen typische Qualitätsmerkmale von Daten und können diese erläutern.

- Sicherheit und Privacy
- Benutzbarkeit
- Zuverlässigkeit
- Verfügbarkeit

[[LZ-12-4]] 
==== LZ 12-4 - Datenzugriff und -berechtigungen
Die Teilnehmer:innen kennen die Notwendigkeit einer Definition, wer Zugang zu welchen Daten hat und unter welchen Bedingungen.
Die Teilnehmer:innen wissen, wie Daten auditiert und gemonitored werden können und kennen die Wichtigkeit der Auditierung für die Bereiche Security, Privacy, Benutzbarkeit und Zuverlässigkeit.

[[LZ-12-5]]
==== LZ 12-5 - Data Stewardship und Ownership
Die Teilnehmer:innen verstehen die Notwendigkeit von dedizierten Verantwortlichen für Datenpflege und -verwaltung. Dies beinhaltet die Definition von Verantwortlichkeiten für Datenqualität, Datenschutz und andere Governance-Aspekte.
Die Teilnehmer:innen können die verschiedenen Rollen und Verantwortungsbereiche in der Data Governence nennen und beschreiben.
Die Teilnehmer:innen wissen, dass es immer einen Datenverantwortlichen geben muss und welche Pflichten dieser hat.

[[LZ-12-6]]
==== LZ 12-6 - Data Contracts
Die Teilnehmer:innen kennen Data Contracts und verstehen wie sie beim Abgleich der Anforderungen von Datenkonsumenten und Datenproduzenten verwendet werden können.

[[LZ-12-7]]
==== LZ 12-7 - Policies
Die Teilnehmer:innen kennen lokale und globale Policies für Daten und wissen wie sie diese festlegen und dokumentieren.

[[LZ-12-8]]
==== LZ 12-8 - Metadaten
Die Teilnehmer:innen verstehen die Bedeutung von Metadaten im Lebenszyklus der Daten und kennen Möglichkeiten, diese zu erheben und festzuhalten.
Sie kennen verschiedene Kategorien von Metadaten und können diese unterscheiden:

- Business Metadaten
- Technische Metadaten
- Betriebs-Metadaten
- Referenzielle Metadaten
- Data Lineage

Die Teilnehmer:innen kennen insbesondere die Bedeutung von Data-Lineage-Metadaten.
Sie sind sich der Bedeutung von Datenschemata bewusst und kennen die diesbezüglichen Unterschiede zwischen verschiedenen Speichersystemen, wie z.B. Object Store und Data Warehouse.


// end::DE[]

// tag::EN[]
[[LG-12-1]]
==== LG 12-1: Definition
tbd.

[[LG-12-2]]
==== LG 12-2 - Privacy, Compliance, Data Security
tbd.

[[LG-12-3]]
==== LG 12-3 - Data Quality
tbd.

[[LG-12-5]]
==== LG 12-5 - Data Stewardship und Ownership
tbd.

[[LG-12-6]]
==== LG 12-6 - Data Contracts
tbd.

[[LG-12-7]]
==== LG 12-7 - Policies
tbd.

[[LG-12-8]]
==== LG 12-8 - Metadata
tbd.


// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
