=== {learning-goals}


// tag::DE[]
[[LZ-1-5]]
==== LZ 12-1 - Qualität von Daten
Die Teilnehmer:innen kennen typische Qualitätsmerkmale von Daten und können diese erläutern:

[frame=none, grid=none]
|===
a|
- Genauigkeit
- Verfügbarkeit
- Vollständigkeit
- Aktualität
- Konsistenz
- Privatheit
- Sicherheit
- Vergleichbarkeit
- Granularität
- Glaubwürdigkeit a|
- Plausibilität
- Validität
- Relevanz
- Nützlichkeit
- Eindeutigkeit
- Zuverlässigkeit
- Konformität
- Einheitlichkeit
- Dauerhaftigkeit
- Interpretierbarkeit
|===


Die Teilnehmer:innen verstehen, warum die Gewährleistung von Datenqualität bei analytischen Daten eine besondere Herausforderung ist. Sie kennen Beispiele für Verfahren zur Prüfung, Gewährleistung und Verbesserung analytischer Daten wie etwa:

- Identifikation von Entitäten und Deduplizierung
- Rechtschreibprüfung und -korrektur
- Schema Vorgabe und Anwendung (Data Constraints)
- Prüfsummen
- Beschreibende fachliche Metadaten
- (Standard-) Datenaustauschformate
- Erkennen von Ausreißern (Outlier Detection), fehlenden Werten und Widersprüchen
// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 12-1: Data Quality
tbd.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
