=== {learning-goals}


// tag::DE[]

[[LZ-11-1]]
==== LZ 11-1 - Übergreifende Themen zum Datenlebenszyklus
Die Teilnehmer:innen verstehen, dass insbesondere die folgenden Themen übergreifend über die einzelnen Phasen des Datenlebenszyklus hinweg beachtet werden müssen:
- Data Governance
- Datensicherheit
- Datenqualität
- Betriebsaspekte (DataOps)

[[LZ-11-2]]
==== LZ 11-2 - Data Governance
Die Teilnehmer:innen verstehen, dass Data Governance eine Vielzahl von Prinzipien und Praktiken umfasst, die sicherstellen, dass Daten im gesamten Lebenszyklus von der Erstellung bis zur Löschung sicher, effektiv und effizient verwaltet werden.
Die Teilnehmer:innen kennen lokale und globale Richtlinien für alle Phasen des Datenlebenszyklus und wissen wie sie diese festlegen und dokumentieren.

[[LZ-11-3]]
==== LZ 11-3 - Data Stewardship und Ownership
Die Teilnehmer:innen verstehen die Notwendigkeit von dedizierten Verantwortlichen für Datenpflege und -verwaltung. Dies beinhaltet die Definition von Verantwortlichkeiten für Datenqualität, Datenschutz und andere Governance-Aspekte.
Die Teilnehmer:innen können die verschiedenen Rollen und Verantwortungsbereiche in der Data Governence nennen und beschreiben.

[[LZ-11-4]]
==== LZ 11-4 - Datenzugriff und -berechtigungen
Die Teilnehmer:innen kennen die Notwendigkeit einer Definition, wer Zugang zu welchen Daten hat und unter welchen Bedingungen.
Die Teilnehmer:innen wissen, wie Daten auditiert und gemonitored werden können und kennen die Wichtigkeit der Auditierung für die Bereiche Security, Privacy, Benutzbarkeit und Zuverlässigkeit.

[[LZ-11-5]]
==== LZ 11-5 - Datenschutz, Compliance, Datensicherheit
Die Teilnehmer:innen kennen Vorgehensweisen und Mechanismen zur Implementierung von Sicherheitsmaßnahmen zum Schutz sensibler Daten.

Die Teilnehmer:innen kennen  gesetzliche und regulatorischer Anforderungen wie die Datenschutz-Grundverordnung (DSGVO) in der EU, das Bundesdatenschutzgesetz (BDSG) in Deutschland oder den California Consumer Privacy Act (CCPA) in den USA.

Die Teilnehmer:innen kennen Mechanismen zum Schutz von Daten vor unbefugtem Zugriff, Verlust oder Diebstahl. Dies umfasst Verschlüsselungsmaßnahmen, Firewalls und anderen Sicherheitstechnologien.
Die Teilnehmer:innen verstehen, welche Daten anonymisiert oder pseudonymisiert werden müssen und kennen die jeweiligen Nutzungsszenarien.
Die Teilnehmer:innen kennen gängige Praktiken zur Anonymisierung und Pseudonymisierung von Daten und wissen, in welchen Fällen diese angewendet werden.

[[LZ-11-6]]
==== LZ 11-6 - Qualität von Daten
Die Teilnehmer:innen verstehen, warum die Gewährleistung von Datenqualität bei analytischen Daten eine besondere Herausforderung ist.
Sie verstehen dass sich die Data Governance darum kümmert die Datenqualität zu gewährleisten.
Die Teilnehmer:innen kennen typische Qualitätsmerkmale von Daten und können diese erläutern.

- Auffindbarkeit
- Benutzbarkeit (Verständlichkeit, Korrektheit)
- Zuverlässigkeit, Verfügbarkeit

[[LZ-11-7]]
==== LZ 11-7 - Data Contracts
Die Teilnehmer:innen wissen, dass ein Data Contract die Struktur, das Format, die Semantik, die Qualität und die Nutzungsbedingungen für den Datenaustausch zwischen einem Datenanbieter und seinen Konsumenten definiert. Ihnen ist bewusst, dass es ist damit ein zentrales Werkzeug ist, damit sich Teams über Daten-Schnittstellen verständigen können und somit Stabilität, Datenqualität und Nachvollziehbarkeit in der Datenarchitektur gewährleisten.
Den Teilnehmer:innen ist bewusst, dass Data Contracts daher trotz des Namens nicht im Sinne eines konkreten Vertrages zwischen einem Datenanbieter und einem Konsumenten zu verstehen sind.

Die Teilnehmer:innen kennen Standards für die Definition von Data Contracts.

[[LZ-11-8]]
==== LZ 11-8 - Metadaten
Die Teilnehmer:innen verstehen die Bedeutung von Metadaten im Lebenszyklus der Daten und kennen Möglichkeiten, diese zu erheben und festzuhalten.
Sie kennen verschiedene Kategorien von Metadaten und können diese unterscheiden:

- Business Metadaten
- Technische Metadaten
- Betriebs-Metadaten
- Referenzielle Metadaten

[[LZ-11-9]]
==== LZ 11-9 - Betriebsaspekte
Die Teilnehmer:innen kennen Vor- und Nachteile von Cloud, On-Premise und Software-as-a-Service. Sie kennen Edge Computing und Content Delivery Networks.
Die Teilnehmer:innen kennen die Grundkonzepte von Containern und Kubernetes.
Die Teilnehmer:innen können Maßnahmen für einen kosteneffizienten Betrieb bennenen.
Die Teilnehmer:innen wissen, wie sie ein effektive Monitoring- und Alerting für datenzentrierte Anwendungen sicherstellen können. Sie verstehen, welche Leistungsmetriken überwacht werden sollten und wie Anomalien erkannt werden können.
Den Teilnehmer:innen ist die Notwendigkeit eines Daten-Lifecycle-Managements mit automatisierten Verfahren und Regeln zur  Qualitätssicherung, zur Transformation, zur Archivierung oder zur Löschung von Daten bewusst.
Die Teilnehmer:innen kennen den Begriff DataOps und verstehen, wie damit agile Methoden auf den Bereich des Data Engineerings übertragen werden.

// end::DE[]

// tag::EN[]
[[LG-12-1]]
==== LG 12-1: Definition
tbd.

[[LG-12-2]]
==== LG 12-2 - Privacy, Compliance, Data Security
tbd.

[[LG-12-3]]
==== LG 12-3 - Data Quality
tbd.

[[LG-12-4]]
==== LG 12-4 - Data Access and Privileges

[[LG-12-5]]
==== LG 12-5 - Data Stewardship und Ownership
tbd.

[[LG-12-6]]
==== LG 12-6 - Data Contracts
tbd.

[[LG-12-7]]
==== LG 12-7 - Policies
tbd.

[[LG-12-8]]
==== LG 12-8 - Metadata
tbd.

[[LG-12-8]]
==== LG 12-8 - Operating
tbd.


// end::EN[]


