=== {learning-goals}


// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Dies ist das erste Lernziel in Kapitel 5, lorem ipsum sit dolor

Hier wird beschrieben, was Teilnehmer:innen in diesem Lernziel lernen sollen. Das kann in Prosa-Text
in ganzen Sätzen oder in Aufzählungen mit Unterpunkten erfolgen. Dabei kann auch unterschieden werden,
wie wichtig einzelne Aspekte des Lernziels sind. Es kann hier bereits auf Literatur verwiesen werden.

* Erstes Teilziel
* Zweites Unterthema
* Dritter Aspekt

[[LZ-5-2]]
==== LZ 5-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.
// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Fundamental structure, building blocks & challenges
tbd.

[[LG-5-2]]
==== LG 5-2: Data pipeline patterns
tbd.

[[LG-5-3]]
==== LG 5-2: Data validation & transformation
tbd.

[[LG-5-4]]
==== LG 5-2: Orchestration & Workflows
tbd.

[[LG-5-5]]
==== LG 5-2: Solutions, infrastructure and operations
tbd.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
